require_relative 'rspec/core'
require_relative 'rspec/support'
require_relative 'rspec/expectations'
require_relative 'rspec/matchers'
require_relative 'rspec/mocks'
require_relative 'rspec/example_groups'
