require_relative 'support/spec'
require_relative 'support/encoded_string'
require_relative 'support/recursive_const_methods'
require_relative 'support/warnings'
require_relative 'support/comparable_version'
