#!/usr/bin/env ruby

# Error codes are taken from /usr/include/sysexits.h

require 'rake'
require 'opal/rspec/runner'
require 'opal/rspec/configuration_parser'

require 'shellwords'

parser = Opal::RSpec::Core::Parser.new(ARGV)
options = parser.parse

case options[:runner]
when String, nil
  runner = Opal::RSpec::Runner.new do |server, config|
    config.runner       = options.delete(:runner)
    config.spec_opts    = options
  end

  runner.run
else
  exit options[:runner].(ARGV, $stderr, $stdout)
end


